# Generated by Django 5.2.7 on 2025-11-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Como o fornecedor deve aparecer nos relatórios.",
                        max_length=255,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Contato principal (opcional).",
                        max_length=254,
                        verbose_name="E-mail",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True,
                        help_text="Telefone ou celular para contato rápido.",
                        max_length=32,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "site",
                    models.URLField(
                        blank=True,
                        help_text="Página oficial ou catálogo online.",
                        verbose_name="Site",
                    ),
                ),
                (
                    "documento",
                    models.CharField(
                        blank=True,
                        help_text="CNPJ, CPF ou outro identificador fiscal.",
                        max_length=32,
                        verbose_name="Documento",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Anote detalhes úteis como horários, contatos secundários etc.",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Use para arquivar fornecedores sem removê-los do histórico.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "ordering": ["nome"],
            },
        ),
    ]
