# Generated by Django 5.2.7 on 2025-11-13 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntregaFornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Resumo curto do que foi entregue (ex.: Adesivos para evento).",
                        max_length=255,
                        verbose_name="Título",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Detalhe o pedido, quantidade, condições ou outros pontos.",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "qualidade",
                    models.IntegerField(
                        choices=[
                            (1, "Excelente"),
                            (2, "Boa"),
                            (3, "Regular"),
                            (4, "Ruim"),
                        ],
                        default=2,
                        help_text="Como você classificaria o resultado desta entrega?",
                        verbose_name="Qualidade percebida",
                    ),
                ),
                (
                    "data_entrega",
                    models.DateField(
                        help_text="Quando o material/serviço foi recebido.",
                        verbose_name="Data da entrega",
                    ),
                ),
                (
                    "valor_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Opcional. Ajuda a comparar orçamentos e custos.",
                        max_digits=10,
                        null=True,
                        verbose_name="Valor estimado",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Notas sobre follow-up, pontos de atenção ou lições aprendidas.",
                        verbose_name="Observações",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="fornecedores.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega do fornecedor",
                "verbose_name_plural": "Entregas dos fornecedores",
                "ordering": ["-data_entrega", "-criado_em"],
            },
        ),
    ]
