# Generated by Django 5.0 on 2024-08-23 19:31

from django.db import migrations, models

import thebook.bookkeeping.models


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_file",
            field=models.FileField(
                upload_to=thebook.bookkeeping.models.document_upload_path
            ),
        ),
    ]
