# Generated by Django 5.0 on 2024-08-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0002_alter_document_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="notes",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
