# Generated by Django 5.1.7 on 2025-04-03 18:31

from django.db import migrations, models

import thebook.reimbursements.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReimbursementRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=254)),
                ("email", models.EmailField(max_length=254)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("payment_info", models.TextField()),
                (
                    "document",
                    models.FileField(
                        upload_to=thebook.reimbursements.models.upload_path
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "received"),
                            (2, "accepted"),
                            (3, "completed"),
                            (4, "rejected"),
                        ],
                        default=1,
                    ),
                ),
            ],
        ),
    ]
