# Generated by Django 5.1.1 on 2024-11-08 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=200, verbose_name="E-Mail")),
                (
                    "has_key",
                    models.BooleanField(
                        default=False, verbose_name="Has physical key?"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Phone number"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="members.member",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start Membership")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="End Membership"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount to be paid in the chosen interval",
                        max_digits=8,
                        verbose_name="Membership Fee",
                    ),
                ),
                (
                    "interval",
                    models.IntegerField(
                        choices=[
                            (1, "Monthly"),
                            (3, "Quarterly"),
                            (6, "Biannually"),
                            (12, "Annually"),
                        ],
                        help_text="How often does the member pay their fees?",
                        verbose_name="Payment Interval",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates is we are expecting to be receiving fees from this membership",
                        verbose_name="Active Membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceivableFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        verbose_name="Expected start date of receiving period"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Due date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Fee Amount"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Paid"), (2, "Unpaid"), (3, "Due")],
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivable_fees",
                        to="members.membership",
                    ),
                ),
            ],
        ),
    ]
