# Generated by Django 5.1.1 on 2024-11-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membership",
            old_name="amount",
            new_name="membership_fee_amount",
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="interval",
            new_name="payment_interval",
        ),
        migrations.AlterField(
            model_name="receivablefee",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Paid"), (2, "Unpaid"), (3, "Due")],
                default=2,
                verbose_name="Payment Status",
            ),
        ),
    ]
