# Generated by Django 5.1.1 on 2024-11-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_rename_amount_membership_membership_fee_amount_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="receivablefee",
            constraint=models.UniqueConstraint(
                fields=("membership", "start_date"),
                name="unique_receivable_fee_in_month",
            ),
        ),
    ]
