# Generated by Django 5.1.3 on 2024-12-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_remove_member_email_alter_member_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Phone number"
            ),
        ),
    ]
