# Generated by Django 5.1.3 on 2024-12-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_alter_member_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="payment_method",
            field=models.IntegerField(
                choices=[(1, "PayPal"), (2, "Pix")],
                default=1,
                help_text="How fees are paid?",
                verbose_name="Payment Method",
            ),
        ),
    ]
