# Generated by Django 5.1.3 on 2024-12-10 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_membership_payment_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["name"]},
        ),
    ]
