# Generated by Django 5.2.2 on 2025-08-06 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookkeeping",
            "0014_remove_categorymatchrule_valid_comparison_function_and_more",
        ),
        ("members", "0008_alter_member_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivablefee",
            name="transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookkeeping.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
    ]
