# Generated by Django 5.2.2 on 2025-08-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_receivablefee_transaction_alter_member_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivableFeeTransactionMatchRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField()),
                ("pattern", models.CharField(max_length=512)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.membership",
                    ),
                ),
            ],
        ),
    ]
