# Generated by Django 5.2.2 on 2025-08-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_receivablefeetransactionmatchrule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receivablefeetransactionmatchrule",
            name="priority",
        ),
    ]
