# Generated by Django 5.2.2 on 2025-08-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_remove_receivablefeetransactionmatchrule_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="Indicates is we are expecting to be receiving fees from this membership",
                verbose_name="Active Membership",
            ),
        ),
    ]
