# Generated by Django 5.2.2 on 2025-09-08 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookkeeping",
            "0014_remove_categorymatchrule_valid_comparison_function_and_more",
        ),
        ("members", "0012_alter_membership_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="payment_method",
            field=models.IntegerField(
                choices=[(1, "PayPal"), (2, "Pix"), (3, "Recurring Pix")],
                default=1,
                help_text="How fees are paid?",
                verbose_name="Payment Method",
            ),
        ),
        migrations.AlterField(
            model_name="receivablefee",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Paid"), (2, "Unpaid"), (3, "Due"), (4, "Skipped")],
                default=2,
                verbose_name="Payment Status",
            ),
        ),
        migrations.AlterField(
            model_name="receivablefee",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookkeeping.transaction",
            ),
        ),
    ]
