# Generated by Django 5.2.10 on 2026-02-09 14:30

import localflavor.br.models

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0013_alter_membership_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="cpf",
            field=localflavor.br.models.BRCNPJField(
                blank=True, default="", max_length=18, verbose_name="CPF"
            ),
        ),
    ]
