# Generated by Django 5.2.10 on 2026-02-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_member_cpf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="cpf",
        ),
    ]
