# Generated by Django 5.2.10 on 2026-02-09 16:25

import localflavor.br.models

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0015_remove_member_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="cpf",
            field=localflavor.br.models.BRCPFField(
                blank=True, default="", max_length=14, verbose_name="CPF"
            ),
        ),
    ]
