# Generated by Django 5.2.10 on 2026-02-13 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0016_member_cpf"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[(1, "Paid"), (2, "Unpaid"), (3, "Due")],
                        verbose_name="Metadata Keys",
                    ),
                ),
                ("value", models.CharField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "unique_together": {("member", "key")},
            },
        ),
    ]
