# Generated by Django 5.2.10 on 2026-02-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0017_membermetadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membermetadata",
            name="key",
            field=models.CharField(
                choices=[(1, "CPF"), (2, "Has physical key"), (3, "PayPal Payer ID")],
                verbose_name="Metadata Keys",
            ),
        ),
    ]
