# Generated by Django 5.2.10 on 2026-04-30 19:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0019_alter_membermetadata_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipForm",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("valid_until", models.DateField()),
            ],
        ),
    ]
