# Generated by Django 5.2.10 on 2026-04-30 19:14

from django.db import migrations, models

import thebook.members.models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0020_membershipform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipform",
            name="valid_until",
            field=models.DateField(default=thebook.members.models.get_valid_until),
        ),
    ]
