# Generated by Django 5.2.13 on 2026-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0021_alter_membershipform_valid_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipform",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
