# Generated by Django 5.2.2 on 2025-09-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpenPixWebhookPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thebook_token", models.CharField()),
                ("payload", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
