# Generated by Django 5.2.9 on 2025-12-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="openpixwebhookpayload",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Received"), (2, "Processed")],
                default=1,
                verbose_name="Processing Status",
            ),
        ),
    ]
