# Generated by Django 5.2.9 on 2025-12-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_openpixwebhookpayload_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaypalWebhookPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.CharField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Received"), (2, "Processed")],
                        default=1,
                        verbose_name="Processing Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
