# Generated by Django 5.2.9 on 2025-12-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_paypalwebhookpayload"),
    ]

    operations = [
        migrations.AddField(
            model_name="paypalwebhookpayload",
            name="correlation_id",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paypalwebhookpayload",
            name="paypal_auth_algo",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paypalwebhookpayload",
            name="paypal_auth_version",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paypalwebhookpayload",
            name="paypal_cert_url",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paypalwebhookpayload",
            name="paypal_transmission_id",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paypalwebhookpayload",
            name="paypal_transmission_sig",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paypalwebhookpayload",
            name="paypal_transmission_time",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
