# Generated by Django 5.2.10 on 2026-02-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0004_paypalwebhookpayload_correlation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openpixwebhookpayload",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Received"), (2, "Processed"), (3, "Unparsable")],
                default=1,
                verbose_name="Processing Status",
            ),
        ),
        migrations.AlterField(
            model_name="paypalwebhookpayload",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Received"), (2, "Processed"), (3, "Unparsable")],
                default=1,
                verbose_name="Processing Status",
            ),
        ),
    ]
