# Generated by Django 5.2.10 on 2026-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0005_alter_openpixwebhookpayload_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paypalwebhookpayload",
            name="internal_notes",
            field=models.CharField(blank=True),
        ),
    ]
