# Generated by Django 5.2.10 on 2026-02-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0006_paypalwebhookpayload_internal_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openpixwebhookpayload",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Received"),
                    (2, "Processed"),
                    (3, "Unparsable"),
                    (4, "Duplicated"),
                ],
                default=1,
                verbose_name="Processing Status",
            ),
        ),
        migrations.AlterField(
            model_name="paypalwebhookpayload",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Received"),
                    (2, "Processed"),
                    (3, "Unparsable"),
                    (4, "Duplicated"),
                ],
                default=1,
                verbose_name="Processing Status",
            ),
        ),
    ]
