# Generated by Django 5.2.10 on 2026-02-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0007_alter_openpixwebhookpayload_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paypalwebhookpayload",
            name="webhook_id",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
