# Generated by Django 5.1.1 on 2024-09-30 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "categories"},
        ),
    ]
