# Generated by Django 5.1.1 on 2024-09-30 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["date", "description"]},
        ),
    ]
