# Generated by Django 5.1.1 on 2024-10-01 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0003_alter_transaction_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashbook",
            options={"ordering": ["name"]},
        ),
    ]
