# Generated by Django 5.1.1 on 2024-10-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0004_alter_cashbook_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbook",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
