# Generated by Django 5.1.3 on 2024-12-02 17:15

import taggit.managers

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0006_transaction_tags"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
