# Generated by Django 5.1.4 on 2024-12-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0008_alter_document_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="notes",
            field=models.CharField(max_length=128),
        ),
    ]
