# Generated by Django 5.1.4 on 2025-02-12 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0010_transaction_transaction_date_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="bookkeeping.transaction",
            ),
        ),
    ]
