# Generated by Django 5.1.4 on 2025-02-12 21:41

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookkeeping", "0011_alter_document_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_date",
            field=models.DateField(default=datetime.date(2011, 10, 12)),
            preserve_default=False,
        ),
    ]
