# Generated by Django 5.2 on 2025-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0013_categorymatchrule"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="categorymatchrule",
            name="valid_comparison_function",
        ),
        migrations.AlterField(
            model_name="categorymatchrule",
            name="comparison_function",
            field=models.CharField(
                blank=True,
                choices=[("EQ", "EQ"), ("NEQ", "NEQ"), ("LTE", "LTE"), ("GTE", "GTE")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="categorymatchrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("comparison_function__isnull", True),
                    models.Q(
                        ("comparison_function__isnull", False),
                        ("comparison_function__in", ["EQ", "NEQ", "LTE", "GTE"]),
                    ),
                    _connector="OR",
                ),
                name="valid_comparison_function",
            ),
        ),
    ]
