# Generated by Django 5.2.7 on 2026-02-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookkeeping",
            "0014_remove_categorymatchrule_valid_comparison_function_and_more",
        ),
        ("fornecedores", "0002_entregafornecedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="fornecedores.fornecedor",
                verbose_name="Fornecedor",
            ),
        ),
    ]
