# Generated by Django 5.2.9 on 2026-01-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bookkeeping",
            "0014_remove_categorymatchrule_valid_comparison_function_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CashBook",
            new_name="BankAccount",
        ),
    ]
