# Generated by Django 5.2.9 on 2026-01-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0015_rename_cashbook_bankaccount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="cash_book",
            new_name="bank_account",
        ),
    ]
