# Generated by Django 5.2.10 on 2026-02-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0016_rename_cash_book_transaction_bank_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="bank_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="bookkeeping.bankaccount",
            ),
        ),
    ]
