# Generated by Django 5.2.10 on 2026-02-05 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0015_transaction_fornecedor"),
        ("bookkeeping", "0018_alter_transaction_bank_account"),
    ]

    operations = []
