# Generated by Django 5.2.10 on 2026-02-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0019_document_content_type_document_object_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorymatchrule",
            name="priority",
        ),
    ]
