# Generated by Django 5.2.10 on 2026-03-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeping", "0020_remove_categorymatchrule_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Source of the transaction (e.g. manual, paypal-webhook, etc.)",
            ),
        ),
    ]
