name: Cora - Process Mailbox

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  schedule:
    name: 📩 Cora - Process Mailbox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl ssh console -C "python manage.py cora__process_mailbox"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
